language: python

python:
  - 3.6

env:
  - DJANGO=2.1.2

install:
  - pip3 install -r requirements.txt
  - pip3 install coveralls

before_script:
  - python manage.py makemigrations
  - python manage.py migrate

script:
  - python manage.py check
  - coverage run --source="base, registration, accounts, posts" manage.py test

after_success:
  coveralls  


notifications:
  email:
    recipients:
      - coderdude1999@gmail.com

    on_success: change
    on_failure: always
